name: getx_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  auto_height_grid_view: ^1.0.0
  awesome_dio_interceptor: ^1.2.0
  build_runner: ^2.4.9
  cached_network_image: ^3.4.0
  chips_choice: ^3.0.1
  cloud_firestore: ^5.2.0
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  datetime_picker_formfield_new: ^2.1.0
  dio: ^5.4.1
  dotted_border: ^2.1.0
  dotted_line: ^3.2.2
  dropdown_button2: ^2.3.9
  firebase_core: ^3.2.0
  firebase_database: ^11.0.3
  firebase_messaging: ^15.0.4
  floating_bottom_bar: ^0.0.3
  flutter:
    sdk: flutter
  flutter_dash: ^1.0.0
  flutter_form_builder: ^9.2.1
  flutter_local_notifications: ^17.2.1+2
  flutter_localization: ^0.2.0
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^8.1.0
  flutter_svg: ^2.0.10+1
  form_builder_validators: ^9.1.0
  get: ^4.6.6
  get_cli: 1.8.1
  get_storage: ^2.1.1
  google_fonts: ^6.1.0
  group_button: ^5.3.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  intl: ^0.18.1
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  lottie: ^3.1.2
  mockito: ^5.4.4
  pull_to_refresh_flutter3: ^2.0.2
  quickalert: ^1.1.0
  shared_preferences: ^2.2.3
  side_sheet: ^1.0.4
  sqflite: ^2.3.3+1
  swipe_refresh: ^1.1.2

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/image/
    - assets/icon/
    - assets/lottie/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/font/Poppins-Regular.ttf
        - asset: assets/font/Poppins-Bold.ttf
          style: italic
        - asset: assets/font/Poppins-Bold.ttf
          weight: 700
    - family: Inter
      fonts:
        - asset: assets/font/Inter-Regular.ttf
        - asset: assets/font/Inter-Bold.ttf
          style: italic
        - asset: assets/font/Poppins-Bold.ttf
          weight: 700
